.TH imgfetch 1 "version 2.0"
.SH NAME
imgfetch - file fetching utility for various image-hosting websites, [danbooru.domnai.us]

.SH SYNOPSIS
.B imgfetch [ options ] [subcommand]
.PP

.SH DESCRIPTION
Download image batchs from a website. 

.SH OPTIONS
.TP
.BR \-h "," \-\-help
Show a help message and exit
.TP
.BR \-q "," \-\-quiet
Disable verbose output
.TP
.BR \-v "," \-\-verbose
Enable verbose output
.TP
.BR \-o "," \-\-output =\fIdir\fR
Specify a directory to download to. Must be specified with this flag or else command will fail.

.SH SUBCOMMAND OPTIONS
Please see the manpage for each subcommand, it will be the same name as the subcommand.

.SH SUBCOMMANDS
.TP 
.B imgfetch-danbooru
Syncronize a local directory with a danbooru tag search url.

.SH BUGS
Please report bugs by emailing me at toddgaunt@protonmail.ch, or fix them yourself and make a pull request to https://www.github.com/toddgaunt/imgfetch if you've got nothing better to do.

.SH AUTHOR
This man page and imgfetch itself were originally authored by Todd Gaunt.
