.TH IMGFETCH 1 imgfetch
.SH NAME
imgfetch - File fetching utility.

.SH SYNOPSIS
.B imgfetch [-h] [-v] [-q] [-o <path>] SUBCOMMAND
.PP

.SH DESCRIPTION
Download image batches from a website specified with
.IR subcommand . 

.SH OPTIONS
.TP
.B \-h
Show a help message and exit.
.TP
.B \-q
Lower the verbosity of output. Can be flagged multiple times.
.TP
.B \-v
Increase the verbosity of output. Can be flagged multiple times.
.TP
.B \-o <path>
Specify a directory to download to. Default is current directory ('.').

.SH SUBCOMMAND OPTIONS
Please see the manpage for each subcommand, detailed at the end of this
document.

.SH SUBCOMMANDS
.TP 
.B imgfetch-danbooru
Syncronize a local directory with a danbooru tag search url.

.SH BUGS
Please report bugs by emailing me at toddgaunt@protonmail.ch, or fix them
yourself and make a pull request to https://www.github.com/toddgaunt/imgfetch
if you've got nothing better to do.

.SH AUTHOR
This man page and imgfetch itself were originally authored by Todd Gaunt.

.SH SEE ALSO
.BR imgfetch-danbooru (1)
